#!/bin/bash

if [ $1 ]; then
    port=$1
else
    port=8888
fi

docker rm -f jetbrains;
docker run --detach \
                --restart always \
                --publish $port:8888 \
                --name jetbrains \
                imhuwq/jetbrains

echo ""
docker port jetbrains

echo ""
echo "The service has been started successfully, here are the logs: "
echo ""

docker logs -f jetbrains;
