#!/bin/bash

if [ $1 ]; then
    port=$1
else
    port=8888
fi

sudo docker rm -f jet_brains;
sudo docker run -d -p $port:8888 --name jet_brains imhuwq/jet_brains

echo ""
sudo docker port jet_brains

echo ""
echo "The service has been started successfully, here are the logs: "
echo ""

sudo docker logs -f jet_brains;
