#!/bin/bash

if [ $1 ]; then
    port=$1
else
    port=8888
fi

sudo docker rm -f jetbrains;
sudo docker run --detach \
                --restart always \
                --publish $port:8888 \
                --name jetbrains \
                imhuwq/jetbrains

echo ""
sudo docker port jetbrains

echo ""
echo "The service has been started successfully, here are the logs: "
echo ""

sudo docker logs -f jetbrains;
